spring:
  application:
    name: zuul-hperson
server:
  port: 8666
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.hperson.com/eureka/
zuul:
  ignoredServices: '*'
  routes:
      DEMO-CLIENT: /api/**
#    ribbonapi:
#      path: /ribbonapi/**
#      serviceId: eureka-ribbon-client
#    feignapi:
#      path: /feignapi/**
#      serviceId: eureka-feign-client
